spring.application.name=api

#DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smartflux}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-ddl=true

# Exibe os valores reais dos parâmetros (?) no console
#logging.level.org.hibernate.orm.jdbc.bind=trace

#Swagger
springdoc.packages-to-scan=com.smartflux.api.controller

# LLM Service
smartflux.llm.url=${LLM_SERVICE_URL:http://localhost:8000}

# E-mail (SMTP Outlook por padrão)
spring.mail.host=${SPRING_MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:aedf6b001@smtp-brevo.com}
spring.mail.password=${MAIL_PASSWORD:xsmtpsib-e38d7f48274e93e8ad11db2bf2841cc50d63ba1d3e2d9d813604f64577a3869b-NHldaYGYiLAlsH47}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true

# E-mail remetente real (O e-mail que você usou para criar a conta no Brevo)
app.mail.from=${MAIL_FROM:smartflux1@outlook.com}

# URL do frontend para o link de reset
app.frontend.url=${FRONTEND_URL:http://localhost:3000}
